Preserve buffetfsm binary on make clean
The Dockerfile in this repo deletes the llvm build files after building
buffet, which means it cannot be rebuilt inside the running container.

- This commit allows zcc to continue without rebuilding buffet, if an
existing buffetfsm binary is available.

- This commit also prevents the buffetfsm binary from being blown away
on running `make clean` in the pepper directory.

diff --git a/compiler/zcc b/compiler/zcc
--- a/compiler/zcc
+++ b/compiler/zcc
@@ -165,7 +165,15 @@ if [ "$extension" == "c" ]; then
           if [ $? != 0 ]; then
           {
               echo "Failed to build FSM transformer. Please make sure you have compiled LLVM."
-              exit 1
+
+              if [ ! -f buffetfsm ]; then
+              {
+                echo "FSM transformer not found. Terminating"
+                exit 1
+              }
+              else
+                echo "Found existing FSM transformer binary. Continuing without recompilation."
+              fi
           } fi
 
           cd ..
